version: 0.2
 
phases:
  pre_build:
    commands:
      - echo starting pre_build `date`
      - echo Delete target Directory - mvn clean - not needed is clean because codebuild creates new
      - echo Validate project correctness
      - mvn validate      
  build:
    commands:
      - echo Installing package into local Repository
      - mvn install
      - echo compiling source code, classes stored in target/classes
      - mvn compile
      - echo packaging into distributable format, e.g. JAR, WAR
      - mvn package
  post_build:
    commands:
      - echo running tests
      - mvn test
      - echo verify that package complies with quality criteria
      - mvn verify
      - echo deploy — copies the final package to the remote repository - not yet implemented    
      - echo build complete `date`
artifacts:
  files:
    - target/dev-lab5-0.0.1-SNAPSHOT.jar
    